language: java
jdk: openjdk8
env:
  global:
  - secure: TQZGDK1eLnY/PFC41ESFRob0dfmhIehuY9n3OVu3gUKrLjEZS5VqTWczx54jrtB0bHH46ZogthATjpaJwgOoAI2AuqHiz3reCAgKA4XE/gGhgiIDLUTUg+fbG6frEPRjWB/OBamCWIip3pB6Acm/nqczFCAVfK2OIyQZvyCGFO0=
  - secure: E/b1Py2L8TaCfHIBskdm0RgjcvPjKwjE7CTcKoiTR6TI4fSb2CKjBJBNRW2spFG825OttGKNoaWlIFBTMnXYGswUnuTfQlL/ngTct62nlMQ1H8YI2+2UQ61R2q9vbl5DeREzrXzHrSTX7qPx4m5rwCmvA5D7suKdzqgz7ToIQ6I=

addons:
  coverity_scan:
    project:
      name: stevespringett/dependency-track
      description: Dependency-Track Coverity Scan
    notification_email: Steve.Springett@owasp.org
    build_command_prepend:
    build_command: mvn clean package
    branch_pattern: coverity_scan
  sonarcloud:
    organization: "dependencytrack"
    token:
      secure: A2WvgrmCiiwS8k2ofWXL+LtRlLKtmDlEjjngQRRqj1Uk/p5CLsNHI65Nb8kpLJq83JpxmqK51KBJlC9ZuCVXSGWAx4pleouz4l8vp5qi38RzBTgUlhUXr5rGjDMpxsQZtDguC4/j+DmPSxDTdyDKsnXvwSJbboRAhrfPRqAzxJ4=

before_install:
  - java -version
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.5/codacy-coverage-reporter-4.0.5-assembly.jar
  - export DOCKLE_VERSION=$(curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
  - wget -O ~/dockle.tar.gz https://github.com/goodwithtech/dockle/releases/download/v${DOCKLE_VERSION}/dockle_${DOCKLE_VERSION}_Linux-64bit.tar.gz
  - tar zxvf ~/dockle.tar.gz -C ~/
  - export TRIVY_VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
  - wget -O ~/trivy.tar.gz https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
  - tar zxvf ~/trivy.tar.gz -C ~/

cache:
  directories:
    - $HOME/.cache/trivy
    - $HOME/.m2

before_script:
  - export REPO=owasp/dependency-track
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "snapshot"; else echo $TRAVIS_BRANCH ; fi`

script:
  - mvn clean package
  # - mvn clean package sonar:sonar -Dsonar.host.url=https://sonarcloud.io
  - mvn package -Dmaven.test.skip=true -P embedded-jetty -Dlogback.configuration.file=src/main/docker/logback.xml
  - docker build -f src/main/docker/Dockerfile -t $REPO:$TAG .
  # TODO: - ~/dockle --exit-code 1 $REPO:$TAG
  - ~/dockle $REPO:$TAG
  - ~/trivy --exit-code 0 --quiet --auto-refresh $REPO:$TAG
  - ~/trivy --exit-code 1 --severity CRITICAL --quiet --auto-refresh $REPO:$TAG

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" AND "$TRAVIS_PULL_REQUEST" == "false" ]; then
    - java -jar ~/codacy-coverage-reporter-assembly.jar report -l Java -r target/jacoco-ut/jacoco.xml
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push $REPO:$TAG;
    fi

notifications:
  slack:
    secure: FtU/UJX7A904c3JgrQ9AE5zYWO8gIMhzAfL8MFRbUd2AfFbNNpb1OaEbIr61Ho0V/HpBYiL/4YDaINKhy/VeUyz1hqAQingvwip6XrblpoEV2bGXZNVOLW72/z41qNwZ2q7Ebx3F1L1jHSUUPBs91FaqWWpwVNXi5FWPT7OkGv0=
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ade5cc3a87ec0ea4d2c8
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
